version: '3'

services:
  hofladen:
    build:
      context: .
    environment:
      MIX_ENV: dev
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: hofladen
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: